import React from 'react';
import { 
  Box, 
  Container, 
  Typography, 
  Button, 
  Paper, 
  Grid,
  Card,
  CardContent,
  CardActions,
  useTheme,
  useMediaQuery
} from '@mui/material';
import { useNavigate } from 'react-router-dom';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import CompareArrowsIcon from '@mui/icons-material/CompareArrows';
import { styled } from '@mui/material/styles';

const StyledCard = styled(Card)(({ theme }) => ({
  height: '100%',
  display: 'flex',
  flexDirection: 'column',
  transition: 'transform 0.3s ease-in-out',
  '&:hover': {
    transform: 'translateY(-8px)',
    boxShadow: theme.shadows[8],
  },
}));

const FeatureCard = styled(Box)(({ theme }) => ({
  display: 'flex',
  alignItems: 'center',
  marginBottom: theme.spacing(2),
  padding: theme.spacing(2),
  borderRadius: theme.shape.borderRadius,
  backgroundColor: theme.palette.background.paper,
  boxShadow: theme.shadows[1],
}));

function Home() {
  const navigate = useNavigate();
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));

  return (
    <Box sx={{ 
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
      py: 8
    }}>
      <Container maxWidth="lg">
        {/* Header Section */}
        <Box sx={{ textAlign: 'center', mb: 8 }}>
          <Typography 
            variant="h2" fontSize={50}
            component="h1" 
            gutterBottom
            sx={{ 
              fontWeight: 'bold',
              background: 'linear-gradient(45deg, #2196F3 30%, #21CBF3 90%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
            }}
          >
            Plagiarism & AI Content Analyzer
          </Typography>
          <Typography 
            variant="h5" 
            color="text.secondary" 
            sx={{ mb: 4, maxWidth: '800px', mx: 'auto' }}
          >
            Advanced tools for detecting AI-generated content and analyzing text similarity
          </Typography>
        </Box>

        {/* Main Features Section */}
        <Grid container spacing={4} sx={{ mb: 8 }}>
          <Grid item xs={12} md={6}>
            <StyledCard>
              <CardContent sx={{ flexGrow: 1 }}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
                  <AutoAwesomeIcon sx={{ fontSize: 40, color: 'primary.main', mr: 2 }} />
                  <Typography variant="h5" component="h2">
                    AI Content Detection
                  </Typography>
                </Box>
                <Typography variant="body1" color="text.secondary" paragraph>
                  Analyze text content to determine if it was generated by AI. Our advanced algorithm examines various linguistic patterns and writing styles.
                </Typography>
                <Box sx={{ mt: 2 }}>
                  <FeatureCard>
                    <Typography variant="body2" sx={{ flex: 1 }}>
                      • Pattern Analysis
                    </Typography>
                  </FeatureCard>
                  <FeatureCard>
                    <Typography variant="body2" sx={{ flex: 1 }}>
                      • Structure Analysis
                    </Typography>
                  </FeatureCard>
                  <FeatureCard>
                    <Typography variant="body2" sx={{ flex: 1 }}>
                      • Style Analysis
                    </Typography>
                  </FeatureCard>
                </Box>
              </CardContent>
              <CardActions sx={{ p: 2 }}>
                <Button
                  fullWidth
                  variant="contained"
                  size="large"
                  onClick={() => navigate('/ai-detection')}
                  startIcon={<AutoAwesomeIcon />}
                >
                  Try AI Detection
                </Button>
              </CardActions>
            </StyledCard>
          </Grid>

          <Grid item xs={12} md={6}>
            <StyledCard>
              <CardContent sx={{ flexGrow: 1 }}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
                  <CompareArrowsIcon sx={{ fontSize: 40, color: 'secondary.main', mr: 2 }} />
                  <Typography variant="h5" component="h2">
                    Similarity Analysis
                  </Typography>
                </Box>
                <Typography variant="body1" color="text.secondary" paragraph>
                  Compare two pieces of text to determine their similarity. Perfect for checking content originality and detecting potential plagiarism.
                </Typography>
                <Box sx={{ mt: 2 }}>
                  <FeatureCard>
                    <Typography variant="body2" sx={{ flex: 1 }}>
                      • Text Comparison
                    </Typography>
                  </FeatureCard>
                  <FeatureCard>
                    <Typography variant="body2" sx={{ flex: 1 }}>
                      • Similarity Score
                    </Typography>
                  </FeatureCard>
                  <FeatureCard>
                    <Typography variant="body2" sx={{ flex: 1 }}>
                      • Detailed Analysis
                    </Typography>
                  </FeatureCard>
                </Box>
              </CardContent>
              <CardActions sx={{ p: 2 }}>
                <Button
                  fullWidth
                  variant="contained"
                  color="secondary"
                  size="large"
                  onClick={() => navigate('/similarity')}
                  startIcon={<CompareArrowsIcon />}
                >
                  Try Similarity Analysis
                </Button>
              </CardActions>
            </StyledCard>
          </Grid>
        </Grid>

        {/* How It Works Section */}
        <Box sx={{ textAlign: 'center', mb: 8 }}>
          <Typography variant="h4" gutterBottom>
            How It Works
          </Typography>
          <Grid container spacing={4} sx={{ mt: 2 }}>
            <Grid item xs={12} md={4}>
              <Paper sx={{ p: 3, height: '100%' }}>
                <Typography variant="h6" gutterBottom>1. Input Text</Typography>
                <Typography variant="body2" color="text.secondary">
                  Enter your text or upload a document for analysis
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={12} md={4}>
              <Paper sx={{ p: 3, height: '100%' }}>
                <Typography variant="h6" gutterBottom>2. Analysis</Typography>
                <Typography variant="body2" color="text.secondary">
                  Our algorithms process the text using multiple analysis methods
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={12} md={4}>
              <Paper sx={{ p: 3, height: '100%' }}>
                <Typography variant="h6" gutterBottom>3. Results</Typography>
                <Typography variant="body2" color="text.secondary">
                  Get detailed results with visual representations
                </Typography>
              </Paper>
            </Grid>
          </Grid>
        </Box>
        
      </Container>
    </Box>
  );
}

export default Home; 